# Generated by Django 3.1.2 on 2021-02-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('phone_number', models.IntegerField(default=0)),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
    ]
