# Generated by Django 3.1.2 on 2021-02-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='costumer',
        ),
    ]
