# Generated by Django 3.1.2 on 2021-02-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210204_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='costumer',
            new_name='user',
        ),
    ]
