# Generated by Django 3.1.2 on 2021-02-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210207_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
    ]
